
{$i deltics.inc}

{$ifdef debug_Deltics_ADO}
  {$define debug_Deltics_ADO_Command}
  {$define debug_Deltics_ADO_Connection}
  {$define debug_Deltics_ADO_ConnectionString}
  {$define debug_Deltics_ADO_DataSource}
  {$define debug_Deltics_ADO_DataSource_JET}
  {$define debug_Deltics_ADO_DataSource_Oracle}
  {$define debug_Deltics_ADO_DataSource_SQLServer}
  {$define debug_Deltics_ADO_Fields}
  {$define debug_Deltics_ADO_MetaData}
  {$define debug_Deltics_ADO_Parameters}
  {$define debug_Deltics_ADO_Properties}
  {$define debug_Deltics_ADO_Provider_Adapter}
  {$define debug_Deltics_ADO_Providers}
  {$define debug_Deltics_ADO_Query}
  {$define debug_Deltics_ADO_Recordset}
  {$define debug_Deltics_ADO_TypeLibrary}
  {$define debug_Deltics_ADO_Utils}
{$endif}

