
{$i deltics.inc}

{$ifdef deltics_rtl}

  {$define deltics_classes}
  {$define deltics_commandline}
  {$define deltics_dateutils}
  {$define deltics_finalizer}
  {$define deltics_hpc}
  {$define deltics_imagelists}
  {$define deltics_json}
  {$define deltics_messagehandler}
  {$define deltics_multicast}
  {$define deltics_oscillator}
  {$define deltics_rtti}
  {$define deltics_sizegrip}
  {$define deltics_statelist}
  {$define deltics_strings}
  {$define deltics_strutils}
  {$define deltics_sysutils}
  {$define deltics_threads}
  {$define deltics_types}
  {$define deltics_versioninfo}
  {$define deltics_vmt}
  {$define deltics_windows}

{$endif}
